# Script for large non-admin dataset seeding.
#
# Run with:
#   mix run priv/repo/seeds_bulk.exs
#
# This script creates:
# - 100 users (coach + regular user, no admins)
# - 200 goals (mixed privacy)
# - 100 challenges total (includes templates and personal challenges)
# - mixed visibility policies for users/goals/challenges
#
# It is safe to rerun: users generated by this script are removed first.

alias HeadsUp.Repo
alias HeadsUp.Auth
alias HeadsUp.Users
alias HeadsUp.Group
alias HeadsUp.Goal
alias HeadsUp.Friendship

alias HeadsUp.Challenges.{
  Challenge,
  ChallengeCategory,
  ChallengeParticipant
}

import Ecto.Query

seed_email_like = "seed.bulk+%@example.com"
seed_password = "seedpassword1234"

users_count = 100
coaches_count = 20
goals_count = 200
challenges_count = 100
templates_count = 35

user_privacy_cycle = ["public", "friends_only", "private"]
goal_privacy_cycle = [:public, :friends, :private]
challenge_visibility_cycle = [:public, :friends, :private]

subscription_cycle = ["free", "pro_3", "pro_5", "unlimited"]
goal_status_cycle = [:active, :active, :completed, :paused, :cancelled]
challenge_status_cycle = [:active, :active, :completed, :paused]
challenge_type_cycle = [:custom, :predefined]

user_images = [
  "/images/user-1.png",
  "/images/user-2.png",
  "/images/user-3.png",
  "/images/user-4.png"
]

goal_images = [
  "/images/goal-fitness-1.png",
  "/images/goal-fitness-2.png",
  "/images/goal-career-1.png",
  "/images/goal-career-2.png",
  "/images/goal-personal-1.png",
  "/images/goal-personal-2.png",
  "/images/goal-finance-1.png",
  "/images/goal-finance-2.png"
]

pick = fn list, index ->
  Enum.at(list, rem(index, length(list)))
end

maybe_add_completed_at = fn attrs, challenge ->
  if challenge.status == :completed do
    Map.put(attrs, :completed_at, DateTime.utc_now())
  else
    attrs
  end
end

ensure_group = fn attrs ->
  case Repo.get_by(Group, name: attrs.name) do
    nil ->
      %Group{}
      |> Group.changeset(attrs)
      |> Repo.insert!()

    group ->
      group
      |> Group.changeset(attrs)
      |> Repo.update!()
  end
end

ensure_category = fn attrs ->
  case Repo.get_by(ChallengeCategory, name: attrs.name) do
    nil ->
      %ChallengeCategory{}
      |> ChallengeCategory.changeset(attrs)
      |> Repo.insert!()

    category ->
      category
      |> ChallengeCategory.changeset(attrs)
      |> Repo.update!()
  end
end

IO.puts("[1/6] Cleaning previously generated seed users...")

seeded_user_ids =
  from(u in Users,
    where: like(u.email, ^seed_email_like),
    select: u.id
  )
  |> Repo.all()

if seeded_user_ids != [] do
  from(u in Users, where: u.id in ^seeded_user_ids)
  |> Repo.delete_all()
end

IO.puts("[2/6] Ensuring goal groups and challenge categories...")

group_specs = [
  %{
    name: "Seed Fitness & Health",
    description: "Seeded fitness goals and routines",
    image_path: "/images/goal-fitness-1.png",
    status: :published
  },
  %{
    name: "Seed Career",
    description: "Seeded career and learning goals",
    image_path: "/images/goal-career-1.png",
    status: :published
  },
  %{
    name: "Seed Personal Growth",
    description: "Seeded personal growth goals",
    image_path: "/images/goal-personal-1.png",
    status: :published
  },
  %{
    name: "Seed Finance",
    description: "Seeded financial goals and planning",
    image_path: "/images/goal-finance-1.png",
    status: :published
  },
  %{
    name: "Seed Wellness",
    description: "Seeded wellness and habit goals",
    image_path: "/images/goal-fitness-2.png",
    status: :published
  },
  %{
    name: "Seed Productivity",
    description: "Seeded productivity and routine goals",
    image_path: "/images/goal-career-2.png",
    status: :published
  }
]

groups = Enum.map(group_specs, ensure_group)

category_specs = [
  %{
    name: "Seed Challenge Fitness",
    description: "Fitness challenge templates",
    image_path: "/images/goal-fitness-1.png",
    status: :active,
    order: 1
  },
  %{
    name: "Seed Challenge Career",
    description: "Career challenge templates",
    image_path: "/images/goal-career-1.png",
    status: :active,
    order: 2
  },
  %{
    name: "Seed Challenge Personal",
    description: "Personal challenge templates",
    image_path: "/images/goal-personal-1.png",
    status: :active,
    order: 3
  },
  %{
    name: "Seed Challenge Finance",
    description: "Finance challenge templates",
    image_path: "/images/goal-finance-1.png",
    status: :active,
    order: 4
  },
  %{
    name: "Seed Challenge Mindset",
    description: "Mindset and consistency challenges",
    image_path: "/images/goal-personal-2.png",
    status: :active,
    order: 5
  }
]

categories = Enum.map(category_specs, ensure_category)

IO.puts("[3/6] Creating users (coach + regular, no admins)...")

users =
  for i <- 1..users_count do
    role = if i <= coaches_count, do: "coach", else: "user"

    attrs = %{
      email: "seed.bulk+#{i}@example.com",
      password: seed_password,
      user_name: "seed_user_#{i}",
      name: "Seed User #{i}",
      bio: "Seeded #{role} profile ##{i}",
      about: "Generated seed user with #{role} role and privacy policy variation",
      level: 1 + rem(i, 50),
      image_path: pick.(user_images, i - 1),
      goal_amount: 0,
      role: role,
      privacy: pick.(user_privacy_cycle, i - 1),
      subscription_type: pick.(subscription_cycle, i - 1),
      xp: rem(i * 37, 5_000)
    }

    {:ok, user} = Auth.register_user(attrs)

    user
    |> Users.confirm_changeset()
    |> Repo.update!()
  end

coach_users = Enum.take(users, coaches_count)
regular_users = Enum.drop(users, coaches_count)

IO.puts("[4/6] Creating accepted friendships for friends-only visibility coverage...")

for i <- 0..(length(users) - 1) do
  user_a = Enum.at(users, i)
  user_b = Enum.at(users, rem(i + 1, length(users)))
  user_c = Enum.at(users, rem(i + 7, length(users)))

  for {left, right} <- [{user_a, user_b}, {user_a, user_c}] do
    %Friendship{}
    |> Friendship.changeset(%{
      user_id: left.id,
      friend_id: right.id,
      status: "accepted"
    })
    |> Repo.insert(on_conflict: :nothing, conflict_target: [:user_id, :friend_id])
  end
end

IO.puts("[5/6] Creating goals with mixed visibility policies...")

goals =
  for i <- 1..goals_count do
    owner = pick.(users, i - 1)
    group = pick.(groups, i - 1)
    status = pick.(goal_status_cycle, i - 1)

    progress =
      case status do
        :completed -> 100
        :active -> rem(i * 9, 95)
        :paused -> rem(i * 7, 85)
        :cancelled -> rem(i * 5, 70)
        _ -> rem(i * 3, 100)
      end

    target_date =
      DateTime.utc_now()
      |> DateTime.add((30 + i) * 86_400, :second)
      |> DateTime.truncate(:second)

    %Goal{}
    |> Goal.changeset(%{
      title: "Seed Goal #{i}",
      description: "Generated goal ##{i} for seeded privacy and role testing",
      big_description:
        "Long-form description for Seed Goal #{i}. This record exists to test browsing and visibility policies across roles.",
      status: status,
      privacy: pick.(goal_privacy_cycle, i - 1),
      target_date: target_date,
      progress: progress,
      image_path: pick.(goal_images, i - 1),
      group_id: group.id,
      user_id: owner.id
    })
    |> Repo.insert!()
  end

goal_counts_by_user = goals |> Enum.frequencies_by(& &1.user_id)

Enum.each(users, fn user ->
  user
  |> Users.changeset(%{goal_amount: Map.get(goal_counts_by_user, user.id, 0)})
  |> Repo.update!()
end)

IO.puts("[6/6] Creating challenge templates and personal challenges...")

templates =
  for i <- 1..templates_count do
    creator =
      if rem(i, 2) == 0 do
        pick.(coach_users, i - 1)
      else
        pick.(regular_users, i - 1)
      end

    type = pick.(challenge_type_cycle, i - 1)
    visibility = pick.(challenge_visibility_cycle, i - 1)
    category = pick.(categories, i - 1)

    base_attrs = %{
      title: "Seed Template #{i}",
      description: "Generated challenge template ##{i}",
      type: type,
      visibility: visibility,
      status: :active,
      image_path: pick.(goal_images, i - 1),
      creator_user_id: creator.id,
      category_id: category.id,
      is_template: true
    }

    attrs =
      case type do
        :predefined ->
          Map.put(base_attrs, :duration_days, 14 + rem(i, 50))

        :custom ->
          start_date = Date.add(Date.utc_today(), -rem(i, 20))
          end_date = Date.add(start_date, 14 + rem(i, 30))

          base_attrs
          |> Map.put(:start_date, start_date)
          |> Map.put(:end_date, end_date)
      end

    %Challenge{}
    |> Challenge.changeset(attrs)
    |> Repo.insert!()
  end

personal_challenge_count = challenges_count - templates_count

personal_challenges =
  for i <- 1..personal_challenge_count do
    creator = pick.(regular_users, i - 1)
    status = pick.(challenge_status_cycle, i - 1)
    visibility = pick.(challenge_visibility_cycle, i - 1)
    from_template? = rem(i, 3) == 0

    attrs =
      if from_template? do
        template = pick.(templates, i - 1)
        start_date = Date.add(Date.utc_today(), -rem(i, 15))

        end_date =
          case template.type do
            :predefined ->
              Date.add(start_date, template.duration_days || 30)

            :custom ->
              template_length =
                if template.start_date && template.end_date do
                  max(1, Date.diff(template.end_date, template.start_date))
                else
                  30
                end

              Date.add(start_date, template_length)
          end

        %{
          title: "Seed Challenge #{i} (from template)",
          description: "Generated personal challenge from template ##{template.id}",
          type: template.type,
          visibility: visibility,
          status: status,
          image_path: pick.(goal_images, i - 1),
          creator_user_id: creator.id,
          category_id: template.category_id,
          template_id: template.id,
          start_date: start_date,
          end_date: end_date,
          is_template: false
        }
      else
        type = pick.(challenge_type_cycle, i - 1)
        category = pick.(categories, i - 1)
        start_date = Date.add(Date.utc_today(), -rem(i, 12))
        end_date = Date.add(start_date, 10 + rem(i, 40))

        %{
          title: "Seed Challenge #{i}",
          description: "Generated personal challenge ##{i}",
          type: type,
          visibility: visibility,
          status: status,
          image_path: pick.(goal_images, i - 1),
          creator_user_id: creator.id,
          category_id: category.id,
          start_date: start_date,
          end_date: end_date,
          is_template: false
        }
      end

    %Challenge{}
    |> Challenge.changeset(attrs)
    |> Repo.insert!()
  end

Enum.each(personal_challenges, fn challenge ->
  start_date = challenge.start_date || Date.utc_today()

  end_date =
    cond do
      challenge.end_date ->
        challenge.end_date

      challenge.type == :predefined ->
        Date.add(start_date, challenge.duration_days || 30)

      true ->
        Date.add(start_date, 30)
    end

  participant_attrs =
    maybe_add_completed_at.(
      %{
        challenge_id: challenge.id,
        user_id: challenge.creator_user_id,
        status: if(challenge.status == :completed, do: :completed, else: :active),
        start_date: start_date,
        end_date: end_date,
        joined_at: DateTime.utc_now()
      },
      challenge
    )

  %ChallengeParticipant{}
  |> ChallengeParticipant.changeset(participant_attrs)
  |> Repo.insert(on_conflict: :nothing, conflict_target: [:challenge_id, :user_id])
end)

IO.puts("""
Bulk seed complete
  Users: #{length(users)} (coach: #{length(coach_users)}, regular: #{length(regular_users)}, admin: 0)
  Goals: #{length(goals)}
  Challenges: #{length(templates) + length(personal_challenges)} (templates: #{length(templates)}, personal: #{length(personal_challenges)})
  User privacy policies: #{Enum.join(user_privacy_cycle, ", ")}
  Goal privacy policies: #{Enum.map_join(goal_privacy_cycle, ", ", &to_string/1)}
  Challenge visibility policies: #{Enum.map_join(challenge_visibility_cycle, ", ", &to_string/1)}
""")
